version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8u212-stretch
      
    steps:

      - checkout

      - run: git submodule update --init

   
      - run: mvn clean package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/chestcommands-plugin*.jar
