version: 2
jobs:
  build:

    working_directory: ~/chestcommands

    docker:
      - image: circleci/openjdk:8u212-stretch
      
   steps:
   
      - run: mvn clean package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/ChestCommands-3.2.0.jar
